---
name: 'OPI Integration CI'

on:
  push:
    branches: [ main ]
    paths:
      - 'integration/**'
      - '.github/workflows/poc-integration.yml'
  pull_request:
    branches: [ main ]
    paths:
      - 'integration/**'
      - '.github/workflows/poc-integration.yml'

concurrency:
  # if workflow for PR or push is already running stop it, and start new one
  group: poc-integration-${{ github.ref }}
  cancel-in-progress: true

jobs:
  integration-shellcheck:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: integration shellcheck
      run: |
        make -C integration shellcheck

  run_integration_poc:
    needs: integration-shellcheck
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Build & Start DPU containers
      run: ./scripts/integration.sh -a dpu build-start
      working-directory: integration

    - name: Run DPU Integration Tests
      run: ./scripts/integration.sh -a dpu run-tests
      working-directory: integration

    - name: DPU Logs
      if: failure()
      run: ./scripts/integration.sh -a dpu logs
      working-directory: integration

    - name: Stop DPU containers
      if: always()
      run: ./scripts/integration.sh -a dpu stop
      working-directory: integration

    - name: Build & Start IPU containers
      run: ./scripts/integration.sh -a ipu build-start
      working-directory: integration

    - name: Run IPU Integration Tests
      run: ./scripts/integration.sh -a ipu run-tests
      working-directory: integration

    - name: IPU Logs
      if: failure()
      run: ./scripts/integration.sh -a ipu logs
      working-directory: integration

    - name: Stop IPU containers
      if: always()
      run: ./scripts/integration.sh -a ipu stop
      working-directory: integration
